#!/bin/bash

set -TEeuo pipefail

BASE_DIR="$(readlink --canonicalize-existing -- "$0")"
BASE_DIR="$(dirname -- "$BASE_DIR")"
declare -r BASE_DIR

"$IDEA_HOME/bin/idea.sh" inspect "$BASE_DIR" "$BASE_DIR/idea-code-inspections.xml" "$BASE_DIR" -v0 -d "$BASE_DIR/src" -format xml
