#!/bin/bash

set -TEeuo pipefail

BASE_DIR="$(readlink --canonicalize-existing -- "$0")"
BASE_DIR="$(dirname -- "$BASE_DIR")"
declare -r BASE_DIR

"$IDEA_HOME/bin/idea.sh" format -s "$BASE_DIR/idea-code-style.xml" -r "$BASE_DIR/src" "$BASE_DIR/pom.xml"
