#!/bin/sh

VERSION='2.16.1'

mvn \
	org.codehaus.mojo:versions-maven-plugin:"$VERSION":display-dependency-updates \
	org.codehaus.mojo:versions-maven-plugin:"$VERSION":display-plugin-updates \
	org.codehaus.mojo:versions-maven-plugin:"$VERSION":display-extension-updates \
	org.codehaus.mojo:versions-maven-plugin:"$VERSION":display-parent-updates \
	org.codehaus.mojo:versions-maven-plugin:"$VERSION":display-property-updates
